version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: acme_dev
    ports:
      - "5432:5432"
    command: -p 5432
